# Site settings
title:          Mariel Carreño
#description:    "Mariel Carreño. Writing about coding, maths, distributed systems, performance optimisation, blockchain."
baseurl:        ""
url:            "https://mvcarreno.github.io"

# Author
author:
  name:         Mariel Carreño
  url:          https://mvcarreno.github.io
  email:        mariel.carreno@gmail.com

data.text.index.coming_soon: COMING SOON

# Build settings
markdown:       kramdown
sass:
  sass_dir:     _sass
  style:        compressed
plugins:
  - jekyll-feed
  - jekyll-paginate
permalink:      /:year-:month-:day/:title
paginate:       369
enable_mathjax: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: mvcarreno-blog

# Social icons
show_social_icons: true
github_username: mvcarreno
reddit_username: mvcarreno
bitbucket_username:
stackoverflow_id:
twitter_username: mvcarreno
skype_username:
steam_nickname:
google_plus_id:
linkedin_username: mvcarreno
angellist_username:
medium_id: mvcarreno
bitcoin_url:
paypal_url:
flattr_button:
telegram_username:
vk_id:

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: true
share_hackernews: true
text.share_buttons.text: "UN SUPER TEXTO"
